export const catDogIdentifierAbi = [
  {
    type: "function",
    name: "fnCnnCatsDogsAddBiasAndRelu",
    inputs: [
      { name: "start_filter_idx", type: "uint16", internalType: "uint16" },
      { name: "batch_size", type: "uint16", internalType: "uint16" },
      { name: "continue_execution", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsAllocateIm2Col",
    inputs: [
      { name: "continue_execution", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsConv",
    inputs: [
      { name: "start_col", type: "uint16", internalType: "uint16" },
      { name: "batch_size", type: "uint16", internalType: "uint16" },
      { name: "continue_execution", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsConvert2DTo3D",
    inputs: [
      { name: "continue_execution", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsDenseApply",
    inputs: [
      { name: "continue_execution", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsFlatten",
    inputs: [
      { name: "continue_execution", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsIm2Col",
    inputs: [
      { name: "continue_execution", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsMaxPool2D",
    inputs: [
      { name: "continue_execution", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsNorm",
    inputs: [
      { name: "start_channel_id", type: "uint16", internalType: "uint16" },
      { name: "batch_size", type: "uint16", internalType: "uint16" },
      { name: "continue_execution", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsPredict",
    inputs: [
      { name: "pixels", type: "uint8[]", internalType: "uint8[]" },
      { name: "continue_execution", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsSetDense1BiasConst",
    inputs: [
      { name: "bias", type: "int64[]", internalType: "int64[]" },
      { name: "gamma", type: "int64[]", internalType: "int64[]" },
      { name: "beta", type: "int64[]", internalType: "int64[]" },
      { name: "mean", type: "int64[]", internalType: "int64[]" },
      { name: "variance", type: "int64[]", internalType: "int64[]" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsSetDense1WeightConst",
    inputs: [
      { name: "filters", type: "int32[][]", internalType: "int32[][]" },
      { name: "row_start", type: "uint16", internalType: "uint16" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsSetDense2Const",
    inputs: [
      { name: "filters", type: "int64[][]", internalType: "int64[][]" },
      { name: "bias", type: "int64[]", internalType: "int64[]" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsSetLayerBias",
    inputs: [
      { name: "layer", type: "uint8", internalType: "uint8" },
      { name: "bias", type: "int64[]", internalType: "int64[]" },
      { name: "gamma", type: "int64[]", internalType: "int64[]" },
      { name: "beta", type: "int64[]", internalType: "int64[]" },
      { name: "mean", type: "int64[]", internalType: "int64[]" },
      { name: "variance", type: "int64[]", internalType: "int64[]" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnCnnCatsDogsSetLayerFilters",
    inputs: [
      { name: "layer", type: "uint8", internalType: "uint8" },
      { name: "filters", type: "int64[][]", internalType: "int64[][]" },
      { name: "row_start", type: "uint16", internalType: "uint16" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [{ name: "_mirror", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mirror",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "onMessageSent",
    inputs: [
      { name: "id", type: "bytes32", internalType: "bytes32" },
      { name: "destination", type: "address", internalType: "address" },
      { name: "payload", type: "bytes", internalType: "bytes" },
      { name: "value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "onReplySent",
    inputs: [
      { name: "destination", type: "address", internalType: "address" },
      { name: "payload", type: "bytes", internalType: "bytes" },
      { name: "value", type: "uint128", internalType: "uint128" },
      { name: "replyTo", type: "bytes32", internalType: "bytes32" },
      { name: "replyCode", type: "bytes4", internalType: "bytes4" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sendMessage",
    inputs: [
      { name: "_payload", type: "bytes", internalType: "bytes" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "event",
    name: "CnnCatsDogsAddBiasAndReluReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsAllocateIm2ColReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsConvReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsConvert2DTo3DReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsDenseApplyReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsFlattenReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsIm2ColReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsMaxPool2DReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsNormReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsPredictReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsSetDense1BiasConstReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsSetDense1WeightConstReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsSetDense2ConstReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsSetLayerBiasReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CnnCatsDogsSetLayerFiltersReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ErrorReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OnMessageEvent",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      { name: "_id", type: "bytes32", indexed: false, internalType: "bytes32" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OnReplyEvent",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
];
