export const digitRecognitionAbi = [
  {
    type: "function",
    name: "fnDigitRecognitionConv2",
    inputs: [
      { name: "continue_calc", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnDigitRecognitionFinish",
    inputs: [{ name: "_value", type: "uint128", internalType: "uint128" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnDigitRecognitionPredict",
    inputs: [
      { name: "pixels", type: "uint16[]", internalType: "uint16[]" },
      { name: "continue_calc", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [{ name: "_mirror", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mirror",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "onMessageSent",
    inputs: [
      { name: "id", type: "bytes32", internalType: "bytes32" },
      { name: "destination", type: "address", internalType: "address" },
      { name: "payload", type: "bytes", internalType: "bytes" },
      { name: "value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "onReplySent",
    inputs: [
      { name: "destination", type: "address", internalType: "address" },
      { name: "payload", type: "bytes", internalType: "bytes" },
      { name: "value", type: "uint128", internalType: "uint128" },
      { name: "replyTo", type: "bytes32", internalType: "bytes32" },
      { name: "replyCode", type: "bytes4", internalType: "bytes4" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sendMessage",
    inputs: [
      { name: "_payload", type: "bytes", internalType: "bytes" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "event",
    name: "DigitRecognitionConv2Reply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DigitRecognitionFinishReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DigitRecognitionPredictReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ErrorReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OnMessageEvent",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      { name: "_id", type: "bytes32", indexed: false, internalType: "bytes32" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OnReplyEvent",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
];
