export const digitRecognitionAbi = [
  {
    type: "function",
    name: "fnDigitRecognitionConv",
    inputs: [
      { name: "start_col", type: "uint16", internalType: "uint16" },
      { name: "batch_size", type: "uint16", internalType: "uint16" },
      { name: "continue_execution", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnDigitRecognitionConvert2DTo3D",
    inputs: [{ name: "_value", type: "uint128", internalType: "uint128" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnDigitRecognitionFlatten",
    inputs: [{ name: "_value", type: "uint128", internalType: "uint128" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnDigitRecognitionForward",
    inputs: [
      { name: "continue_execution", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnDigitRecognitionIm2Col",
    inputs: [{ name: "_value", type: "uint128", internalType: "uint128" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnDigitRecognitionPredict",
    inputs: [
      { name: "pixels", type: "uint8[]", internalType: "uint8[]" },
      { name: "continue_execution", type: "bool", internalType: "bool" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnDigitRecognitionSetConvLayerBias",
    inputs: [
      { name: "layer", type: "uint8", internalType: "uint8" },
      { name: "bias", type: "int64[]", internalType: "int64[]" },
      { name: "gamma", type: "int64[]", internalType: "int64[]" },
      { name: "beta", type: "int64[]", internalType: "int64[]" },
      { name: "mean", type: "int64[]", internalType: "int64[]" },
      { name: "variance", type: "int64[]", internalType: "int64[]" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnDigitRecognitionSetConvLayerWeights",
    inputs: [
      { name: "layer", type: "uint8", internalType: "uint8" },
      { name: "filters", type: "int64[][]", internalType: "int64[][]" },
      { name: "row_start", type: "uint16", internalType: "uint16" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnDigitRecognitionSetFcLayerBias",
    inputs: [
      { name: "layer", type: "uint8", internalType: "uint8" },
      { name: "bias", type: "int64[]", internalType: "int64[]" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "fnDigitRecognitionSetFcLayerWeights",
    inputs: [
      { name: "layer", type: "uint8", internalType: "uint8" },
      { name: "filters", type: "int64[][]", internalType: "int64[][]" },
      { name: "row_start", type: "uint16", internalType: "uint16" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [{ name: "_mirror", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mirror",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "onMessageSent",
    inputs: [
      { name: "id", type: "bytes32", internalType: "bytes32" },
      { name: "destination", type: "address", internalType: "address" },
      { name: "payload", type: "bytes", internalType: "bytes" },
      { name: "value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "onReplySent",
    inputs: [
      { name: "destination", type: "address", internalType: "address" },
      { name: "payload", type: "bytes", internalType: "bytes" },
      { name: "value", type: "uint128", internalType: "uint128" },
      { name: "replyTo", type: "bytes32", internalType: "bytes32" },
      { name: "replyCode", type: "bytes4", internalType: "bytes4" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sendMessage",
    inputs: [
      { name: "_payload", type: "bytes", internalType: "bytes" },
      { name: "_value", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "event",
    name: "DigitRecognitionConvReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DigitRecognitionConvert2DTo3DReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DigitRecognitionFlattenReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DigitRecognitionForwardReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DigitRecognitionIm2ColReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DigitRecognitionPredictReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DigitRecognitionSetConvLayerBiasReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DigitRecognitionSetConvLayerWeightsReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DigitRecognitionSetFcLayerBiasReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DigitRecognitionSetFcLayerWeightsReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ErrorReply",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OnMessageEvent",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      { name: "_id", type: "bytes32", indexed: false, internalType: "bytes32" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OnReplyEvent",
    inputs: [
      { name: "payload", type: "bytes", indexed: false, internalType: "bytes" },
      {
        name: "_destination",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_value",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "_replyTo",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "_replyCode",
        type: "bytes4",
        indexed: false,
        internalType: "bytes4",
      },
    ],
    anonymous: false,
  },
];
