[package]
name = "orderbook-app"
version = "0.1.0"
edition = "2024"

[dependencies]
sails-rs = { version = "0.9.1", features = ["ethexe"] }
scale-info = { version = "2", default-features = false }
parity-scale-codec = { version = "3", default-features = false }
strum = { version = "0.27", features = ["derive"], default-features = false  }
strum_macros = { version = "0.27", default-features = false  }
