export const abi = [
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes", name: "payload", type: "bytes" },
      {
        indexed: false,
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "_value",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "_replyTo",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes4",
        name: "_replyCode",
        type: "bytes4",
      },
    ],
    name: "ErrorReply",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes", name: "payload", type: "bytes" },
      {
        indexed: false,
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "_value",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "_replyTo",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes4",
        name: "_replyCode",
        type: "bytes4",
      },
    ],
    name: "ManagerAddCheckersReply",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes", name: "payload", type: "bytes" },
      {
        indexed: false,
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "_value",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "_replyTo",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes4",
        name: "_replyCode",
        type: "bytes4",
      },
    ],
    name: "ManagerCheckPointsSetReply",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes", name: "payload", type: "bytes" },
      {
        indexed: false,
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "_value",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "_replyTo",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes4",
        name: "_replyCode",
        type: "bytes4",
      },
    ],
    name: "ManagerGenerateAndStorePointsReply",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes", name: "payload", type: "bytes" },
      {
        indexed: false,
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "_value",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "_replyTo",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes4",
        name: "_replyCode",
        type: "bytes4",
      },
    ],
    name: "ManagerRestartReply",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes", name: "payload", type: "bytes" },
      {
        indexed: false,
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "_value",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "_replyTo",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes4",
        name: "_replyCode",
        type: "bytes4",
      },
    ],
    name: "ManagerResultCalculatedReply",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes", name: "payload", type: "bytes" },
      {
        indexed: false,
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "_value",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "_replyTo",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes4",
        name: "_replyCode",
        type: "bytes4",
      },
    ],
    name: "ManagerSendNextBatchReply",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes", name: "payload", type: "bytes" },
      { indexed: false, internalType: "bytes32", name: "_id", type: "bytes32" },
      {
        indexed: false,
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "_value",
        type: "uint128",
      },
    ],
    name: "OnMessageEvent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "bytes", name: "payload", type: "bytes" },
      {
        indexed: false,
        internalType: "address",
        name: "_destination",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "_value",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "_replyTo",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes4",
        name: "_replyCode",
        type: "bytes4",
      },
    ],
    name: "OnReplyEvent",
    type: "event",
  },
  {
    inputs: [
      { internalType: "bytes32[]", name: "checkers", type: "bytes32[]" },
      { internalType: "uint128", name: "_value", type: "uint128" },
    ],
    name: "fnManagerAddCheckers",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "max_iter", type: "uint32" },
      { internalType: "uint32", name: "batch_size", type: "uint32" },
      { internalType: "bool", name: "continue_checking", type: "bool" },
      { internalType: "uint128", name: "_value", type: "uint128" },
    ],
    name: "fnManagerCheckPointsSet",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "width", type: "uint32" },
      { internalType: "uint32", name: "height", type: "uint32" },
      {
        components: [
          { internalType: "int64", name: "num", type: "int64" },
          { internalType: "uint32", name: "scale", type: "uint32" },
        ],
        internalType: "struct IManager.FixedPoint",
        name: "x_min",
        type: "tuple",
      },
      {
        components: [
          { internalType: "int64", name: "num", type: "int64" },
          { internalType: "uint32", name: "scale", type: "uint32" },
        ],
        internalType: "struct IManager.FixedPoint",
        name: "x_max",
        type: "tuple",
      },
      {
        components: [
          { internalType: "int64", name: "num", type: "int64" },
          { internalType: "uint32", name: "scale", type: "uint32" },
        ],
        internalType: "struct IManager.FixedPoint",
        name: "y_min",
        type: "tuple",
      },
      {
        components: [
          { internalType: "int64", name: "num", type: "int64" },
          { internalType: "uint32", name: "scale", type: "uint32" },
        ],
        internalType: "struct IManager.FixedPoint",
        name: "y_max",
        type: "tuple",
      },
      { internalType: "uint32", name: "points_per_call", type: "uint32" },
      { internalType: "bool", name: "continue_generation", type: "bool" },
      {
        internalType: "bool",
        name: "check_points_after_generation",
        type: "bool",
      },
      { internalType: "uint32", name: "max_iter", type: "uint32" },
      { internalType: "uint32", name: "batch_size", type: "uint32" },
      { internalType: "uint128", name: "_value", type: "uint128" },
    ],
    name: "fnManagerGenerateAndStorePoints",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint128", name: "_value", type: "uint128" }],
    name: "fnManagerRestart",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32[]", name: "indexes", type: "uint32[]" },
      { internalType: "uint32[]", name: "results", type: "uint32[]" },
      { internalType: "uint128", name: "_value", type: "uint128" },
    ],
    name: "fnManagerResultCalculated",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "checker", type: "bytes32" },
      { internalType: "uint32", name: "max_iter", type: "uint32" },
      { internalType: "uint32", name: "batch_size", type: "uint32" },
      { internalType: "uint128", name: "_value", type: "uint128" },
    ],
    name: "fnManagerSendNextBatch",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_mirror", type: "address" }],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "mirror",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "id", type: "bytes32" },
      { internalType: "address", name: "destination", type: "address" },
      { internalType: "bytes", name: "payload", type: "bytes" },
      { internalType: "uint128", name: "value", type: "uint128" },
    ],
    name: "onMessageSent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "destination", type: "address" },
      { internalType: "bytes", name: "payload", type: "bytes" },
      { internalType: "uint128", name: "value", type: "uint128" },
      { internalType: "bytes32", name: "replyTo", type: "bytes32" },
      { internalType: "bytes4", name: "replyCode", type: "bytes4" },
    ],
    name: "onReplySent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes", name: "_payload", type: "bytes" },
      { internalType: "uint128", name: "_value", type: "uint128" },
    ],
    name: "sendMessage",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
